import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
  <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {/* This is Squarespace. */}
  {/* benjamin-hardman */}
  <base href="" />
  <meta charSet="utf-8" />
  <title>Jad Zeitouni</title>
  <meta
    httpEquiv="Accept-CH"
    content="Sec-CH-UA-Platform-Version, Sec-CH-UA-Model"
  />
  <link
    rel="icon"
    type="image/x-icon"
    href="https://images.squarespace-cdn.com/content/v1/57d083042e69cf8d9a5e056e/1563462957656-CIH8FF2PIG24V9ME0Q06/favicon.ico?format=100w"
  />
  <link rel="canonical" href="index.html" />
  <meta property="og:site_name" content="Jad Zeitouni" />
  <meta property="og:title" content="Jad Zeitouni" />
  <meta property="og:url" content="https://benjaminhardman.com" />
  <meta property="og:type" content="website" />
  <meta
    property="og:description"
    content="Imagery from the North | A collection of works by Iceland based photographer Jad Zeitouni."
  />
  <meta
    property="og:image"
    content="http://static1.squarespace.com/static/57d083042e69cf8d9a5e056e/t/67158ea90f88fd4c0dcfea07/1729466043934/IMG_8599-2+5.JPG?format=1500w"
  />
  <meta property="og:image:width" content={1500} />
  <meta property="og:image:height" content={1875} />
  <meta itemProp="name" content="Jad Zeitouni" />
  <meta itemProp="url" content="https://benjaminhardman.com" />
  <meta
    itemProp="description"
    content="Imagery from the North | A collection of works by Iceland based photographer Jad Zeitouni."
  />
  <meta
    itemProp="thumbnailUrl"
    content="http://static1.squarespace.com/static/57d083042e69cf8d9a5e056e/t/67158ea90f88fd4c0dcfea07/1729466043934/IMG_8599-2+5.JPG?format=1500w"
  />
  <link
    rel="image_src"
    href="http://static1.squarespace.com/static/57d083042e69cf8d9a5e056e/t/67158ea90f88fd4c0dcfea07/1729466043934/IMG_8599-2+5.JPG?format=1500w"
  />
  <meta
    itemProp="image"
    content="http://static1.squarespace.com/static/57d083042e69cf8d9a5e056e/t/67158ea90f88fd4c0dcfea07/1729466043934/IMG_8599-2+5.JPG?format=1500w"
  />
  <meta name="twitter:title" content="Jad Zeitouni" />
  <meta
    name="twitter:image"
    content="http://static1.squarespace.com/static/57d083042e69cf8d9a5e056e/t/67158ea90f88fd4c0dcfea07/1729466043934/IMG_8599-2+5.JPG?format=1500w"
  />
  <meta name="twitter:url" content="https://benjaminhardman.com" />
  <meta name="twitter:card" content="summary" />
  <meta
    name="twitter:description"
    content="Imagery from the North | A collection of works by Iceland based photographer Jad Zeitouni."
  />
  <meta
    name="description"
    content="Imagery from the North | A collection of works by Iceland based 
photographer Jad Zeitouni."
  />
  <link rel="preconnect" href="https://images.squarespace-cdn.com" />
  <link
    rel="stylesheet"
    type="text/css"
    href="https://fonts.googleapis.com/css2?family=Archivo+Black:wght@400&family=Space+Grotesk:wght@300;600;700"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="https://static1.squarespace.com/static/versioned-site-css/57d083042e69cf8d9a5e056e/257/5c5a519771c10ba3470d8101/671579b5fa25590d4726d821/1587/site.css"
  />
  {/* Facebook Pixel Code */}
  <noscript>
    &lt;img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1082599388742882&amp;ev=PageView&amp;noscript=1"
    /&gt;
  </noscript>
  {/* End Facebook Pixel Code */}
  {/* Global site tag (gtag.js) - Google Analytics */}
  {/* Google Tag Manager */}
  {/* End Google Tag Manager */}
  {/* End of Squarespace Headers */}
  <link
    rel="stylesheet"
    type="text/css"
    href="https://static1.squarespace.com/static/vta/5c5a519771c10ba3470d8101/versioned-assets/1728407958569-DI71YIND73BBQN7RBZCZ/static.css"
  />
</head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
